### ISSUE TITLE
syrupy does not work with pytest 5.0.1

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#156]
**Describe the bug**

Running syrupy with pytest 5.0.1 produces:

> AttributeError: 'Config' object has no attribute 'invocation_params'

**To Reproduce**

```
pip install pytest==5.0.1 syrupy==0.3.5
echo "def test_example(snapshot):\nassert snapshot == 'hi'" > test_file.py
pytest
```

If we don't support 5.0.1, we should be explicit about min versions.
